### ISSUE TITLE
Change VM name for Hyper-V-Manager

### ISSUE THREAD

**Issue by schmunk42** [mitchellh/vagrant#3738]
How can I change the VM name, I tried this locally (virtualbox):
```
vagrantfile-local:
    vm:
        box: 'myname'
        box_url: 'hashicorp/precise64'
```

But got this error:
```
The box you're adding has a name different from the name you
requested. For boxes with metadata, you cannot override the name.
If you're adding a box using `vagrant box add`, don't specify
the `--name` parameter. If the box is being added via a Vagrantfile,
change the `config.vm.box` value to match the name below.
Requested name: myname
Actual name: hashicorp/precise64
```

Which value would I have to change to reflect the box name in the manager?
