### ISSUE TITLE
Ansible provision fails, SSH encountered an unknown error.

### ISSUE THREAD

**Issue by nathanielks** [mitchellh/vagrant#5205]
Heyo!

I'm experiencing a similar issue to #5151. I have 3 machines I'm attempting to provision, 2 of the machines are failing. One continues to work fine. When first provisioning the machine it spat out this debug info:

```
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
```

After halting and restarting, that message doesn't display, however ansible still can't get into the machines.

[Gist of ssh debug log](https://gist.github.com/nathanielks/d709b49c82dca0622bcd)

`vagrant ssh` works fine, it's only when ansible attempts to provision that it fails. Curious, yeah?
