### ISSUE TITLE
Vagrant doesn't propagate `--no-color` option to ansisble provisioner

### ISSUE THREAD

**Issue by marsam** [mitchellh/vagrant#5531]
## Steps to reproduce

1. Create a a Vagrantfile with ansible provisioner:

```ruby
# Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
```

```yaml
# playbook.yml
- hosts: default
  gather_facts: no
  tasks:
    - command: uname -a
```

2. Provision with `--no-color` option:

![](http://i.imgur.com/f997JDS.png)

This error occur because `ANSIBLE_FORCE_COLOR=true` is [harcoded](https://github.com/mitchellh/vagrant/blob/8b8f2b26a6e736e4d77c49c7686c9f0a1a0c2eb2/plugins/provisioners/ansible/provisioner.rb#L71) in the provisioner
