### ISSUE TITLE
Salt provisioner fails to upload minion config

### ISSUE THREAD

**Issue by piohhmy** [mitchellh/vagrant#5973]
Ran into a problem in 1.7.3 doing a vagrant up using a trusty64 box with a salt provisioner specifying a custom minion_config. This is the error:
```
Copying salt minion config to /etc/salt
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the SSH user doesn't have permission
to write to the destination location. Alternately, the user running
Vagrant on the host machine may not have permission to read the file.

Source: /Users/danny/dev/se/one-offs/vagrant/minion.yaml
Dest: /etc/salt/minion
```

It appears that the vagrant user does not have permission by default to scp to /etc/salt/ so provisioning fails.  I confirmed it is possible to vagrant ssh into the machine and change the permissions/owner on /etc/salt/ and then the provisioning will work OK.  

It appears 74d22069d41b35bae50e32c1c68a92a4958afebb may have been the breaking change as it introduced the uploading to /etc/salt.

**Comment by SoftCreatR** [comment]
I can confirm this. We're currently experiencing this issue, too.

**Comment by sephlaire** [comment]
I can confirm this as well. I'm using Vagrant 1.7.3 with VirtualBox 5.0. As a workaround I've been using a shell provisioner with the following to make sure salt in installed and the config is copied over:

```
#!/usr/bin/env bash

echo "Setup saltstack PPA"
sudo apt-get install software-properties-common python-software-properties -y >> /dev/null
sudo add-apt-repository ppa:saltstack/salt -y >> /dev/null
sudo apt-get update >> /dev/null

echo "Installing salt-minion"
sudo apt-get install salt-minion -y >> /dev/null
sudo cp /vagrant/salt/configs/ubuntu.conf /etc/salt/minion

echo "Restart salt-minion"
sudo salt-minion -d
sudo service salt-minion restart
```

**Comment by nmadhok** [comment]
I can confirm this issue. As a workaround, I specified ``config.ssh.username = "root"`` and ``config.ssh.password = "vagrant"`` in my Vagrant file

**Comment by clamor** [comment]
Same issue with provider vmware_desktop.

**Comment by royka** [comment]
I've got this issue too

**Comment by amchoukir** [comment]
I can confirm the issue too

**Comment by sonoranDesert** [comment]
This also started happening to me after upgrading to Vagrant 1.7.4.

**Comment by dwickwire** [comment]
Same experience here using vagrant 1.7.3 and 1.7.4 on both Virtual Box 4.3 and 5 using OSX Yosemite.

**Comment by jake223** [comment]
@sephlaire could you explain your workaround in more detail?

**Comment by sephlaire** [comment]
@jake223 
I have 3 relevant files that I am using to provision the VM. `Vagrantfile`, `server.yaml`, and `ubuntu_bootstrap.sh` which are below. The Vagrantfile is using `vm.provision "shell"` to call the shell script which installs salt and copies over my minion config.  
  
##### Vagrantfile
```ruby
# -*- mode: ruby -*-
# # vi: set ft=ruby :

# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('servers.yaml')

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Iterate through entries in YAML file
  servers.each do |servers|
    config.vm.define servers["name"] do |srv|
      srv.vm.box = servers["box"]
      srv.vm.network "private_network", ip: servers["ip"]
      srv.vm.hostname = servers["hostname"]
      srv.vm.provision "shell", path: servers["bootstrap"] unless servers["bootstrap"].nil?
      srv.vm.network "forwarded_port", guest: servers["guest_port"], host: servers["host_port"] unless servers["guest_port"].nil? || servers["host_port"].nil?
      srv.vm.synced_folder servers["sync-local"], servers["sync-remote"] unless servers["sync-local"].nil? || servers["sync-remote"].nil?
      srv.vm.provider :virtualbox do |vb|
        vb.name = servers["name"]
        vb.memory = servers["ram"]
      end
      unless servers["minion_config"].nil?
       # srv.vm.provision "file", source: servers["minion_config"], destination: "/etc/salt/minion"
        srv.vm.provision :salt do |salt|
          salt.run_highstate = true
          salt.minion_config = servers["minion_config"] 
          salt.minion_key = servers["minion_key"] unless servers["minion_key"].nil?
          salt.minion_pub = servers["minion_pub"] unless servers["minion_pub"].nil?
        end
      end
    end
  end
end
```

##### servers.yaml
```YAML
---
- name: ubuntu
  hostname: ubuntu
  box: ubuntu/trusty64
  ram: 1024
  ip: 10.1.15.11
  bootstrap: ubuntu_bootstrap.sh
  sync-local: ./salt/roots
  sync-remote: /srv/salt
  minion_config: ./salt/configs/ubuntu.conf
  minion_key: ./salt/ssh-key/ubuntu.pem
  minion_pub: ./salt/ssh-key/ubuntu.pub
- name: centos
  hostname: centos
  box: chef/centos-7.0
  ram: 1024
  ip: 10.1.15.12
  bootstrap: centos_bootstrap.sh
  sync-local: ./salt/roots
  sync-remote: /srv/salt 
  minion_config: ./salt/configs/centos.conf
  minion_key: ./salt/ssh-key/centos.pem
  minion_pub: ./salt/ssh-key/centos.pub
```

##### ubunt_bootstrap.sh
```shell
#!/usr/bin/env bash

echo "Setup saltstack PPA"
sudo apt-get install software-properties-common python-software-properties -y >> /dev/null
sudo add-apt-repository ppa:saltstack/salt -y >> /dev/null
sudo apt-get update >> /dev/null

echo "Installing salt-minion"
sudo apt-get install salt-minion -y >> /dev/null
sudo cp /vagrant/salt/configs/ubuntu.conf /etc/salt/minion

echo "Restart salt-minion"
sudo salt-minion -d
sudo service salt-minion restart
sudo salt-call state.highstate
```
