### ISSUE TITLE
volumes_from (docker-compose) seems not to work within vagrant

### ISSUE THREAD

**Issue by Morgy93** [mitchellh/vagrant#6282]
Hello,

I'm refering to https://github.com/andreaskoch/dockerized-magento which basically works pretty well, but I stumbled upon some issue, I assume.
It seems that "volumes_from" doesn't work.

First some of my docker-compose.yml:
````
nginx:
  build: docker-images/nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  domainname: ek.local
  environment:
    DOMAIN: ek.local
    VIRTUAL_HOST: ek.local
    MAGENTO_ROOT: /var/www/html/web
    MAGENTO_DEVELOPERMODE: 1
    SSL_CERTIFICATE_PATH: /etc/ssl/certs/ssl-cert-snakeoil.pem
    SSL_CERTIFICATE_KEY_PATH: /etc/ssl/private/ssl-cert-snakeoil.key
  volumes:
    - //vagrant/docker-images/nginx/server.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
    - //vagrant/docker-images/nginx/server.key:/etc/ssl/private/ssl-cert-snakeoil.key
  volumes_from:
    - php
php:
  build: docker-images/php/5.5-dev
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "solr:solr"
    - "mysql:mysql"
  volumes:
    - //vagrant:/var/www/html
````

Well, to cut it short, the "volumes" defined within php (- //vagrant:/var/www/html) works pretty well.
While looking inside the php container I can see my local files at /var/www/html/web but if I take a look into the nginx container which got volumes_from: - php I don't see anything within /var/www/html/web 
The two volumes defined for nginx are working too by the way .. just volumes_from doesn't work.

Any help?
