### ISSUE TITLE
Vagrant 1.8, ansible_local tasks running as `root` user still require `sudo: yes` to succeed

### ISSUE THREAD

**Issue by elsom25** [mitchellh/vagrant#6727]
Strangely, I have many tasks that used to work when running ansible through the now deprecated `ansibleLocal` because my user is set to `root` for particular role tasks, however, porting this over to the new `ansible_local` in vagrant 1.8, and I have to explicitly add `sudo: yes` to all tasks that require root privileges. This is unexpected.

**Comment by gildegoma** [comment]
Sorry, but I don't know what you're referring with

> the now deprecated ansibleLocal

Having to explicitly set `sudo: yes` (at task or play level) sounds quite reasonable, if you have to execute as a different user.

Could you please provide more details, thanks!

**Comment by elsom25** [comment]
Sorry, the former ansible plugin, `vagrant-ansible-local`, didn't run into this issue. 

For context, my `site.yml` file specifies:

```
---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  roles:
    - common

- name: deploy mariadb
  hosts: raw_db_servers
  remote_user: root
  roles:
    - db-maria

- name: configure the databases
  hosts: db_servers
  remote_user: root
  roles:
    - db-settings

- name: configure and deploy the webservers and application code
  hosts: web_servers
  remote_user: root
  roles:
    - web
```

I've specified that all commands should run as the `root` user, which with the former `vagrant-ansible-local`, seemed to work a-okay. Now, however, it *seems* to not be respecting that fact (or that's my best guess as to why I have to use sudo).

**Comment by gildegoma** [comment]
By default, the `ansibleLocal` [run as `root` user](https://github.com/jaugustin/vagrant-ansible-local/blob/master/lib/vagrant-ansible-local/provisioner.rb#L59-L60), which explains why it worked for you so far.

The new built-in `ansible_local` runs as the [vagrant ssh user](http://docs.vagrantup.com/v2/vagrantfile/ssh_settings.html), and therefore the explicit `sudo` setting is required in your case. Since your roles seem to require root in any environment (not specific to Vagrant), you might better set it in your playbook file, instead as a `Vagrantfile` option:

```yaml
---
- name: apply common configuration to all nodes
  hosts: all
  sudo: yes
  roles:
    - common

...
```

Note that `remote_user` option is not applicable when Ansible is used with `local` transport (unlike with `ssh` or `winrm`).

I'm closing, but please feel free to ask to reopen if you think that something more should be done on Vagrant side.
