### ISSUE TITLE
adding a storage cdrom with an iso using libvirt fails due to duplicate id

### ISSUE THREAD

**Issue by Titerote** [mitchellh/vagrant#7337]
### Vagrant version
Vagrant 1.8.1

### Host operating system
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 23 (Twenty Three)
Release:	23
Codename:	TwentyThree
```

### Guest operating system
```
vagrant box add coreos-alpha https://alpha.release.core-os.net/amd64-usr/1053.2.0/coreos_production_vagrant.box
```

### Vagrantfile
[Vagrantfile.txt](https://github.com/mitchellh/vagrant/files/277311/Vagrantfile.txt)

That vagrant file uses an iso called configdrive.iso, the way to create is is simply:
create a folder called new-drive by running $ mkdir -p new-drive/openstack/latest/
put a cloud-config file under that path, and run

```
$ mkisofs -R -V config-2 -o configdrive.iso new-drive
```

This is my cloud-config:

```
#cloud-config

ssh_authorized_keys:
     - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRk6/xTRumdiCTCukoKuZEfYuh7+I6yDUtBTIRX8ES5OrgRADCImfRBoBKbQW9O75k1j5loHW9BExLkM8RThJ1tu0LbeCepPYkmy+pgD7pbrAL8DAMSUTNbQAnNxCuKc+EmryyQMKDHB/HI4dsHfcx+HgQ3cjUyRu/MMM2FVV/izB6knFVwMITxAlFhscdrrw7qRdC1HL0Ax/a7VhF/OGOaIX7QYsjeI0Q1E1yS4kQA4SMwm5cggcPgRDuI2qbOLs3KY1E9AzJ+gVZR0krFFe5cfaKLdM/Ap1kevlXNchLWs4S+qRbT1osi4zvyZwuIq0R1efawpmhjgRugphbh26B me"

coreos:
        etcd2:
           discovery: "https://discovery.etcd.io/022370a38b784822f213028297d5b950"
           advertise-client-urls: "http://$public_ipv4:2379"
           initial-advertise-peer-urls: "http://$public_ipv4:2380"
           listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
           listen-peer-urls: "http://$public_ipv4:2380,http://$public_ipv4:7001"
        fleet:
           public-ip: $public_ipv4   # used for fleetctl ssh command
        units:
           - name: etcd2.service
             command: start
           - name: fleet.service
             command: start
```

Although the iso doesn't even get mounted/mapped, so it doesn't matter what you put on that iso 

### Debug output
https://gist.github.com/Titerote/5940963ff75d59f69c0668c1566711de

### Expected behavior
I would expect a new vm with a iso attached to it

### Actual behavior
I got an error indicating there is a duplicate id for that device 

### Steps to reproduce
Make sure you have libvirtd installed and running
1. git clone https://github.com/coreos/coreos-vagrant.git
2. cd coreos-vagrant && cp config.rb.sample config.rb && cp user-data.sample user-data
3. vagrant box add coreos-alpha https://alpha.release.core-os.net/amd64-usr/1053.2.0/coreos_production_vagrant.box
4. vagrant plugin install vagrant-mutate && vagrant plugin install vagrant-libvirt
5. vagrant mutate --input-provider=virtualbox  coreos-alpha libvirt### Vagrant version
Vagrant 1.8.1

### Host operating system
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 23 (Twenty Three)
Release:	23
Codename:	TwentyThree

### Guest operating system
vagrant box add coreos-alpha https://alpha.release.core-os.net/amd64-usr/1053.2.0/coreos_production_vagrant.box

### Vagrantfile
[Vagrantfile.txt](https://github.com/mitchellh/vagrant/files/277311/Vagrantfile.txt)

That vagrant file uses an iso called configdrive.iso, the way to create is is simply:
create a folder called new-drive by running $ mkdir -p new-drive/openstack/latest/
put a cloud-config file under that path, and run
$ mkisofs -R -V config-2 -o configdrive.iso new-drive

This is my cloud-config:
#cloud-config

ssh_authorized_keys:
     - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRk6/xTRumdiCTCukoKuZEfYuh7+I6yDUtBTIRX8ES5OrgRADCImfRBoBKbQW9O75k1j5loHW9BExLkM8RThJ1tu0LbeCepPYkmy+pgD7pbrAL8DAMSUTNbQAnNxCuKc+EmryyQMKDHB/HI4dsHfcx+HgQ3cjUyRu/MMM2FVV/izB6knFVwMITxAlFhscdrrw7qRdC1HL0Ax/a7VhF/OGOaIX7QYsjeI0Q1E1yS4kQA4SMwm5cggcPgRDuI2qbOLs3KY1E9AzJ+gVZR0krFFe5cfaKLdM/Ap1kevlXNchLWs4S+qRbT1osi4zvyZwuIq0R1efawpmhjgRugphbh26B me"

coreos:
        etcd2:
           discovery: "https://discovery.etcd.io/022370a38b784822f213028297d5b950"
           advertise-client-urls: "http://$public_ipv4:2379"
           initial-advertise-peer-urls: "http://$public_ipv4:2380"
           listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
           listen-peer-urls: "http://$public_ipv4:2380,http://$public_ipv4:7001"
        fleet:
           public-ip: $public_ipv4   # used for fleetctl ssh command
        units:
           - name: etcd2.service
             command: start
           - name: fleet.service
             command: start

Although the iso doesn't even get mounted/mapped, so it doesn't matter what you put on that iso 

### Debug output
https://gist.github.com/Titerote/5940963ff75d59f69c0668c1566711de

### Expected behavior
I would expect a new vm with a iso attached to it

### Actual behavior
I got an error indicating there is a duplicate id for that device 

### Steps to reproduce
Make sure you have libvirtd installed and running
1. git clone https://github.com/coreos/coreos-vagrant.git
2. cd coreos-vagrant && cp config.rb.sample config.rb && cp user-data.sample user-data
3. vagrant box add coreos-alpha https://alpha.release.core-os.net/amd64-usr/1053.2.0/coreos_production_vagrant.box
4. vagrant plugin install vagrant-mutate && vagrant plugin install vagrant-libvirt
5. vagrant mutate --input-provider=virtualbox  coreos-alpha libvirt
6. -- override the vagranfile from the one I provided
7. VAGRANT_LOG=debug vagrant up --provider libvirt --debug 

### References
I haven't found any on my google searches

6. -- override the vagranfile from the one I provided
7. VAGRANT_LOG=debug vagrant up --provider libvirt --debug 

### References
I haven't found any on my google searches
