### ISSUE TITLE
vagrant-vmware-workstation 4.0.9 fails for shared directory 4.0.8 works

### ISSUE THREAD

**Issue by newtonianb** [mitchellh/vagrant#7381]
**Vagrant**: 1.8.1
**OS**: Windows 10 Pro
**Homestead**: 2.2.1

When I run homestead up (proxy to vagrant up) one of my folders fail below. NOTE this works just fine in vagrant-vmware-workstation (4.0.8) but fails in vagrant-vmware-workstation (4.0.9)

```
vmhgfs-fuse -o uid=`id -u vagrant`,gid=900,allow_other, '.host:/-home-vagrant-Code-my-folder' /home/vagrant/Code/my/folder
```

```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: vmware_workstation

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:\my\other\folder
      to: /home/vagrant/Code/my/other/folder
	  
    - map: C:\my\folder
      to: /home/vagrant/Code/my/folder
            
sites:
    - map: myother.app
      to: /home/vagrant/Code/my/other/folder/public
    - map: my.app
      to: /home/vagrant/Code/my/folder/public

```
