### ISSUE TITLE
[nginx] Warning: Unknown variable

### ISSUE THREAD

**Issue by quoidautre** [mitchellh/vagrant#8394]
Hi, 
I've an error when I just launch my VM : up --provision 

### Vagrant version
1.8.1

### Host operating system
Ubuntu 16.04

### Guest operating system
Ubuntu : 14.04

### Vagrantfile
```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_267k17i7c5ui:
                        id: vm.spectre.id
                        network:
                            private_network: 192.168.56.101
                        hostname: vm.spectre
                        memory: '2048'
                        cpus: '4'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_19mkvk0x71hk:
                source: /var/www/vm
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - vim
        - htop
        - git
        - tree
        - unrar
        - unzip
        - lame
users_groups:
    install: '1'
    groups: {  }
    users:
        - fabrice
locale:
    install: '1'
    settings:
        default_locale: fr_FR.UTF-8
        locales:
            - fr_FR.UTF-8
        timezone: Europe/Paris
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_g9r0lzpdauze:
            server_name: vm.spectre-app_socialnetwork
            www_root: /var/www/app_socialnetwork/web
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
                - app.php
                - app_dev.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_o54uhomj1di3:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_u5e8yyngc04l:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_zfubtum6bzu0:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '7.1'
    modules:
        php:
            - cli
            - intl
            - curl
            - gd
            - fpm
            - geoip
            - json
            - mcrypt
            - mysql
            - memcache
            - memcached
            - mbstring
            - mysqlnd
            - imagick
            - opcache
            - xmlrpc
            - sqlite
            - simplexml
        pear: {  }
        pecl:
            - mongo
            - mongodb
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        'date.timezone = Europe/Paris': Europe/Paris
        date.timezone: Europe/Paris
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_bjt6xvx31iqn:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '1'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_m78s8b4jzq4j:
            default: '1'
            bundler: '1'
            version: 1.9.3
            gems:
                - deep_merge
                - activesupport@4.2.6
                - vine
python:
    install: '1'
    packages: {  }
    versions:
         pyenv_2068nmslt5h9:
            version: 3.4.0
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_69v3sxutnqv0:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_07zofgey2ukw:
            name: dbname
            sql: ''
    grants:
        mariadbng_5vn8puka8hqr:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: '1'
    users: {  }
    databases: {  }
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '1'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '1'
    settings:
        port: '6379'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_zzzk849df2dt:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

### Debug output
```
==> vm.myvm.id: Warning: Unknown variable: '::lsbminordistrelease'. at /tmp/vagrant-puppet/modules-45a543c38ffbdd04eced1334c1ba204b/apt/manifests/params.pp:15:32
==> vm.myvm.id: Warning: Unknown variable: 'nginx::params::nx_global_owner'. at /tmp/vagrant-puppet/modules-45a543c38ffbdd04eced1334c1ba204b/nginx/manifests/init.pp:99:37
==> vm.myvm.id: Warning: Unknown variable: 'nginx::params::nx_global_group'. at /tmp/vagrant-puppet/modules-45a543c38ffbdd04eced1334c1ba204b/nginx/manifests/init.pp:100:37
==> vm.myvm.id: Warning: Unknown variable: 'nginx::params::nx_global_mode'. at /tmp/vagrant-puppet/modules-45a543c38ffbdd04eced1334c1ba204b/nginx/manifests/init.pp:101:37
==> vm.myvm.id: Warning: Unknown variable: 'nginx::params::nx_sites_available_owner'. at /tmp/vagrant-puppet/modules-45a543c38ffbdd04eced1334c1ba204b/nginx/manifests/init.pp:102:37
==> vm.myvm.id: Warning: Unknown variable: 'nginx::params::nx_sites_available_group'. at /tmp/vagrant-puppet/modules-45a543c38ffbdd04eced1334c1ba204b/nginx/manifests/init.pp:103:37
==> vm.myvm.id: Warning: Unknown variable: 'nginx::params::nx_sites_available_mode'. at /tmp/vagrant-puppet/modules-45a543c38ffbdd04eced1334c1ba204b/nginx/manifests/init.pp:104:37
==> vm.myvm.id: Warning: Unknown variable: 'proxy'. at /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812/Nginx.pp:72:25
==> vm.myvm.id: Error: Evaluation Error: No matching entry for selector parameter with value 'Debian' at /tmp/vagrant-puppet/modules-45a543c38ffbdd04eced1334c1ba204b/puphpet/manifests/php/settings.pp:141:15 on node vm.spectre
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

### Expected behavior
It's happend when I do : 
`vagrant up --provision`

### Steps to reproduce
1. vagrant up --provision

Can you help me ?
Thanks

Fabrice

**Comment by quoidautre** [comment]
And, if I change the config.yaml to upgrade the python version like this ?
```
python:
     install: '1'
     packages: {  }
    versions:
          pyenv_2068nmslt5h9:
             version: 3.4.0
```

It's works ?

Fabrice
