### ISSUE TITLE
Use a shared network as the first network card timeout

### ISSUE THREAD

**Issue by starriv** [mitchellh/vagrant#8462]
I use vagrant to run homestead, provider using Parallels provider. The network card is set to share the network will time out

<img width="801" alt="qq20170410-180702 2x" src="https://cloud.githubusercontent.com/assets/7098001/24857009/48f3cbc8-1e19-11e7-88a2-f7b84628ad89.png">

<img width="597" alt="qq20170410-181534 2x" src="https://cloud.githubusercontent.com/assets/7098001/24857115/b7d7058c-1e19-11e7-93ba-92b1c2176b5b.png">

<img width="660" alt="qq20170410-181353 2x" src="https://cloud.githubusercontent.com/assets/7098001/24857058/7db8c930-1e19-11e7-8d7c-58ab509f9e72.png">

### Vagrant version
Vagrant 1.9.3

### Host operating system
macOS Sierra 10.12.4

### Guest operating system
ubuntu 16.04(homestead)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path(File.join(Dir.home, ".homestead"))

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.require_version '>= 1.8.4'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
          s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON.parse(File.read(homesteadJsonPath))
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false
    end

    if defined? VagrantPlugins::HostsUpdater
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    end
end

```
### Homestead file
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: parallels

authorize: ~/.ssh/homestead.pub

keys:
    - ~/.ssh/homestead

folders:
    - map: ~/workspaces
      to: /home/vagrant/workspaces

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public

databases:
    - homestead

```
### Expected behavior
The network is not set to the shared network and will not time out

### Steps to reproduce
1. vagrant up
