### ISSUE TITLE
without vt-x, vagrant boots vms and then hangs on ssh

### ISSUE THREAD

**Issue by dradetsky** [mitchellh/vagrant#8668]
NOTE: I have solved this problem, this just is just about making developer experience better.

### Vagrant version
Vagrant 1.9.5

### Host operating system
arch linux
Linux alap 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux

### Guest operating system
hashicorp/precise64 (ubanto)
tantegerda1/archlinux (arch)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "#{box}"
end
```

### Expected behavior
When `vagrant up`-ing without full requirements enabled (eg vt-x/vt-d enabled in bios), vagrant should immediately fail with the usual `Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes` message, or similar.

### Actual behavior
On some boxes, such as the above arch linux box (not the precise64 box tho), in spite of not having vt-x/vt-d enabled, vagrant boots the box and gets all the way to `default: SSH auth method: private key` before hanging indefinitely and finally failing due to timeout. Subsequently, `vagrant status` reports the box as booted (I think also "running"; i can double-check if it's important).

This is really confusing because if you don't know a ton about the details of virtualization (like me), you'd assume that if the box boots, virtualization is okay. Thus the failure to ssh in must be some kind of network issue, and you start checking firewall rules and whatnot.

### Steps to reproduce
0. run arch linux, setup vagrant (see below)
1. have vt-x/vt-d off in bios
2. try to boot above vm with box=tantegerda1/archlinux

my (ansible-local) vagrant setup:

```yaml

- name: vagrant
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - vagrant
    - virtualbox-host-modules-arch
  become: yes

- name: load virtualbox modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - vboxnetadp
    - vboxnetflt
    - vboxpci
    - vboxdrv
  become: yes
```

### References
appears related to #7217
